/**
 * MASTER DSA PROBLEM DATABASE — single source of truth.
 *
 * Generated from the user-provided spreadsheets:
 *   - 404sheet.xlsx        -> CORE_SECTIONS (the day-by-day / week-by-week roadmap)
 *   - DSA_500 workbook      -> PRACTICE_PROBLEMS (extra practice problems, browsable in the Problems tab)
 *
 * Do NOT hand-edit generated arrays below; re-run scripts/generate-master-problems.md steps
 * (see /mnt/user-data or repo docs) against the source spreadsheets instead.
 *
 * Rules encoded here (do not violate):
 *   - This file (plus practice-problems.ts) is the ONLY place problem data is defined.
 *   - Firebase / Firestore never stores this catalog — only per-user progress that
 *     references these fixed IDs.
 *   - No Striver/TUF fields are stored on problems; TUF is only used at query-time by
 *     the Google/YouTube search helpers (see src/lib/search-links.ts).
 */

import type { Difficulty } from "./types";

export interface MasterProblem {
  /** Fixed, unique, permanent ID — never reassign. */
  id: string;
  name: string;
  difficulty: Difficulty;
  platform: "LeetCode" | "GeeksforGeeks";
  link: string;
  pattern: string;
  /** Roadmap level from 404sheet.xlsx, e.g. "Level 1". */
  level: string;
}

export interface CoreSection {
  topicNo: number;
  topic: string;
  subtopics: string[];
  problems: MasterProblem[];
}

/** The 338-problem core roadmap, grouped by topic in 404sheet.xlsx order. Drives Today / Weeks / Topics. */
export const CORE_SECTIONS: CoreSection[] = [
  {
    topicNo: 1,
    topic: "Programming Fundamentals",
    subtopics: ["Input / Output", "Variables & Data Types", "Operators", "Conditions", "Loops", "Nested Loops", "Functions", "Basic Arrays", "Basic Strings", "Basic Number Problems", "Basic Math", "Time & Space Complexity"],
    problems: [
      { id: "CORE-001-01", name: "Read and Print a Number", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/basic-input-output/", pattern: "Input / Output", level: "Level 1" },
      { id: "CORE-001-02", name: "Basic Data Types", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/cpp/cpp-data-types/", pattern: "Variables / Data Types", level: "Level 1" },
      { id: "CORE-001-03", name: "Basic Arithmetic Operations", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/cpp/cpp-operators/", pattern: "Operators", level: "Level 1" },
      { id: "CORE-001-04", name: "Check Even or Odd", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/check-whether-number-even-odd/", pattern: "Conditionals", level: "Level 1" },
      { id: "CORE-001-05", name: "Find Largest of Three Numbers", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/find-largest-three-elements-array/", pattern: "Conditionals", level: "Level 1" },
      { id: "CORE-001-06", name: "Print Numbers from 1 to N", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/program-print-n-numbers/", pattern: "Loops", level: "Level 1" },
      { id: "CORE-001-07", name: "Sum of First N Natural Numbers", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/sum-of-natural-numbers/", pattern: "Loops", level: "Level 1" },
      { id: "CORE-001-08", name: "Pattern Printing", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/printing-patterns-set-1/", pattern: "Nested Loops", level: "Level 1" },
      { id: "CORE-001-09", name: "Functions in Programming", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/cpp/functions-in-cpp/", pattern: "Functions", level: "Level 1" },
      { id: "CORE-001-10", name: "Array Traversal", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/array-traversal/", pattern: "Arrays", level: "Level 1" },
      { id: "CORE-001-11", name: "String Traversal", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/string-data-structure/", pattern: "Strings", level: "Level 1" },
      { id: "CORE-001-12", name: "Count Digits in a Number", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/program-count-digits-integer-3-different-methods/", pattern: "Math / Digits", level: "Level 1" },
      { id: "CORE-001-13", name: "Sum of Digits", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/program-for-sum-of-the-digits-of-a-given-number/", pattern: "Math / Digits", level: "Level 1" },
      { id: "CORE-001-14", name: "Time and Space Complexity Basics", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/analysis-of-algorithms-set-1-asymptotic-analysis/", pattern: "Complexity Analysis", level: "Level 1" },
    ],
  },
  {
    topicNo: 2,
    topic: "Mathematics",
    subtopics: ["Medium Maths", "Medium", "Prefix Sum + Hashing", "Bitwise XOR", "Easy Maths", "Bit Manipulation Trie", "Easy", "Prime Numbers", "GCD / LCM", "Powers", "Modular Arithmetic"],
    problems: [
      { id: "CORE-002-01", name: "Prime Factors", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/print-all-prime-factors-of-a-given-number/", pattern: "Medium Maths", level: "Level 1" },
      { id: "CORE-002-02", name: "Count Set", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/count-set-bits-in-an-integer/", pattern: "Medium", level: "Level 1" },
      { id: "CORE-002-03", name: "Count with given XOR", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/count-number-subarrays-given-xor/", pattern: "Prefix Sum + Hashing", level: "Level 1" },
      { id: "CORE-002-04", name: "Complement of Base 10 Number", difficulty: "Easy", platform: "LeetCode", link: "https://leetcode.com/problems/complement-of-base-10-integer/", pattern: "Bitwise XOR", level: "Level 1" },
      { id: "CORE-002-05", name: "Single Number III", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/single-number-iii/", pattern: "Bitwise XOR", level: "Level 1" },
      { id: "CORE-002-06", name: "Closest Number", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/find-number-closest-n-divisible-m/", pattern: "Easy Maths", level: "Level 1" },
      { id: "CORE-002-07", name: "Max XOR of Two", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/maximum-xor-of-two-numbers-in-an-array/", pattern: "Bit Manipulation Trie", level: "Level 1" },
      { id: "CORE-002-08", name: "Pairs with XOR less than K", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/count-pairs-having-bitwise-xor-less-than-k-from-given-array/", pattern: "Bit Manipulation Trie", level: "Level 1" },
      { id: "CORE-002-09", name: "Euler's Totient", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/eulers-totient-function/", pattern: "Easy", level: "Level 1" },
      { id: "CORE-002-10", name: "Kth Set Bit", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/check-whether-k-th-bit-set-not/", pattern: "Easy", level: "Level 1" },
      { id: "CORE-002-11", name: "Only set bit", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/find-position-of-the-only-set-bit/", pattern: "Easy", level: "Level 1" },
      { id: "CORE-002-12", name: "nCr", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/program-calculate-value-ncr/", pattern: "Easy", level: "Level 1" },
      { id: "CORE-002-13", name: "Check if a Number is Prime", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/check-whether-number-prime/", pattern: "Prime Check", level: "Level 1" },
      { id: "CORE-002-14", name: "Count Primes — Sieve of Eratosthenes", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/count-primes/", pattern: "Sieve of Eratosthenes", level: "Level 1" },
      { id: "CORE-002-15", name: "GCD of Two Numbers", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/euclidean-algorithms-basic-and-extended/", pattern: "Euclidean Algorithm", level: "Level 1" },
      { id: "CORE-002-16", name: "LCM of Two Numbers", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/lcm-of-two-numbers/", pattern: "GCD / LCM", level: "Level 1" },
      { id: "CORE-002-17", name: "Pow(x, n)", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/powx-n/", pattern: "Fast Exponentiation", level: "Level 2" },
      { id: "CORE-002-18", name: "Modular Exponentiation", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/modular-exponentiation-power-in-modular-arithmetic/", pattern: "Fast Exponentiation / Modulo", level: "Level 2" },
    ],
  },
  {
    topicNo: 3,
    topic: "Sorting",
    subtopics: ["Cycle Sort Based", "Cyclic Sort", "Cyclic Sort (Index-Based)", "Easy", "Easy Array", "Medium", "Merge Sort", "Quick Sort", "Search on Two", "Sorting"],
    problems: [
      { id: "CORE-003-01", name: "Cycle Sort", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/cycle-sort/", pattern: "Cycle Sort Based", level: "Level 1" },
      { id: "CORE-003-02", name: "Min Swaps to Sort", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/minimum-number-swaps-required-sort-array/", pattern: "Cycle Sort Based", level: "Level 1" },
      { id: "CORE-003-03", name: "Find all Duplicate Numbers", difficulty: "Easy", platform: "LeetCode", link: "https://leetcode.com/problems/find-all-duplicates-in-an-array/", pattern: "Cyclic Sort", level: "Level 1" },
      { id: "CORE-003-04", name: "Find the First K Missing Positive Numbers", difficulty: "Hard", platform: "LeetCode", link: "https://leetcode.com/problems/kth-missing-positive-number/", pattern: "Cyclic Sort", level: "Level 1" },
      { id: "CORE-003-05", name: "Set Mismatch", difficulty: "Easy", platform: "LeetCode", link: "https://leetcode.com/problems/set-mismatch/", pattern: "Cyclic Sort (Index-Based)", level: "Level 1" },
      { id: "CORE-003-06", name: "First Missing Positive", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/first-missing-positive/", pattern: "Cyclic Sort (Index-Based)", level: "Level 1" },
      { id: "CORE-003-07", name: "Sort by Length", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/sort-array-strings-according-string-lengths/", pattern: "Easy", level: "Level 1" },
      { id: "CORE-003-08", name: "Wave Form", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/sort-array-wave-form-2/", pattern: "Easy", level: "Level 1" },
      { id: "CORE-003-09", name: "Is Sorted", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/program-check-array-sorted-not-iterative-recursive/", pattern: "Easy Array", level: "Level 1" },
      { id: "CORE-003-10", name: "Merge Overlapping", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/merging-intervals/", pattern: "Medium", level: "Level 1" },
      { id: "CORE-003-11", name: "", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/problems/shop-in-candy-store1145/1", pattern: "Medium", level: "Level 1" },
      { id: "CORE-003-12", name: "Intersection of 2 Sorted", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/intersection-of-two-sorted-arrays/", pattern: "Merge & Merge Sort Based", level: "Level 1" },
      { id: "CORE-003-13", name: "Merge Without Extra Space", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/merge-two-sorted-arrays-o1-extra-space/", pattern: "Merge & Merge Sort Based", level: "Level 1" },
      { id: "CORE-003-14", name: "Quick Sort", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/quick-sort-algorithm/", pattern: "Partition & Quick Sort Based", level: "Level 1" },
      { id: "CORE-003-15", name: "Sort Binary", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/segregate-0s-and-1s-in-an-array-by-traversing-array-once/", pattern: "Partition & Quick Sort Based", level: "Level 1" },
      { id: "CORE-003-16", name: "Kth of two sorted", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/k-th-element-two-sorted-arrays/", pattern: "Search on Two", level: "Level 1" },
      { id: "CORE-003-17", name: "Median of two sorted", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/median-of-two-sorted-arrays/", pattern: "Search on Two", level: "Level 1" },
      { id: "CORE-003-18", name: "Sorting", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/introduction-to-sorting-algorithm/", pattern: "Sorting", level: "Level 1" },
    ],
  },
  {
    topicNo: 4,
    topic: "Arrays — Basics",
    subtopics: ["Linear Search", "Reverse", "Medium Array", "Basics"],
    problems: [
      { id: "CORE-004-01", name: "Second Largest Element", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/find-second-largest-element-array/", pattern: "Linear Search", level: "Level 1" },
      { id: "CORE-004-02", name: "Reverse an Array", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/program-to-reverse-an-array/", pattern: "Easy Array", level: "Level 1" },
      { id: "CORE-004-03", name: "Sum of All Subarrays", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/sum-of-all-subarrays/", pattern: "Medium Array", level: "Level 1" },
      { id: "CORE-004-04", name: "Linear Search", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/linear-search/", pattern: "Foundation", level: "Level 1" },
      { id: "CORE-004-05", name: "Find Minimum and Maximum", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/problems/find-minimum-and-maximum-element-in-an-array4428/1", pattern: "Foundation", level: "Level 1" },
      { id: "CORE-004-06", name: "Third Largest Element", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/third-largest-element-array-distinct-elements/", pattern: "Foundation", level: "Level 1" },
      { id: "CORE-004-07", name: "Rotate Array", difficulty: "Easy", platform: "LeetCode", link: "https://leetcode.com/problems/rotate-array/", pattern: "Foundation", level: "Level 1" },
      { id: "CORE-004-08", name: "Reverse Array in Groups", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/problems/reverse-array-in-groups0255/1", pattern: "Foundation", level: "Level 1" },
      { id: "CORE-004-09", name: "Move All Zeroes to End", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/move-zeroes-end-array/", pattern: "Foundation", level: "Level 1" },
      { id: "CORE-004-10", name: "Maximum Consecutive Ones", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/maximum-consecutive-ones-or-zeros-in-a-binary-array/", pattern: "Foundation", level: "Level 1" },
      { id: "CORE-004-11", name: "Remove Duplicates from Sorted Array", difficulty: "Easy", platform: "LeetCode", link: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/", pattern: "Foundation", level: "Level 1" },
      { id: "CORE-004-12", name: "Array Leaders", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/leaders-in-an-array/", pattern: "Foundation", level: "Level 1" },
      { id: "CORE-004-13", name: "Wave Array", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/check-if-an-array-is-wave-array/", pattern: "Foundation", level: "Level 1" },
      { id: "CORE-004-14", name: "Missing and Repeating in Array", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/find-a-repeating-and-a-missing-number/", pattern: "Foundation", level: "Level 1" },
      { id: "CORE-004-15", name: "Plus One", difficulty: "Easy", platform: "LeetCode", link: "https://leetcode.com/problems/plus-one/", pattern: "Foundation", level: "Level 1" },
      { id: "CORE-004-16", name: "Stock Buy and Sell — One Transaction", difficulty: "Easy", platform: "LeetCode", link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", pattern: "Foundation", level: "Level 1" },
      { id: "CORE-004-17", name: "Rearrange Array Alternately", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/problems/-rearrange-array-alternately-1587115620/0", pattern: "Foundation", level: "Level 1" },
      { id: "CORE-004-18", name: "Find Common Elements in Three Sorted Arrays", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/find-common-elements-three-sorted-arrays/", pattern: "Foundation", level: "Level 1" },
      { id: "CORE-004-19", name: "Maximum Difference Between Two Elements", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/maximum-difference-between-two-elements/", pattern: "Foundation", level: "Level 1" },
      { id: "CORE-004-20", name: "Find the Missing Number", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/find-the-missing-number/", pattern: "Foundation", level: "Level 1" },
    ],
  },
  {
    // NOTE: topicNo intentionally reassigned to 42 (was erroneously 4, colliding with
    // "Arrays — Basics" above). IDs below were CORE-004-01..07, colliding with the
    // Arrays section's IDs of the same name — fixed to CORE-042-01..07, a range not
    // used anywhere else in this file. topicNo/id are not read anywhere outside this
    // file for ordering, so this only fixes the collision and changes nothing else.
    topicNo: 42,
    topic: "Strings — Basics",
    subtopics: ["Easy String", "Medium String", "Palindrome", "Root-to-Leaf Path", "String Manipulation"],
    problems: [
      { id: "CORE-042-01", name: "Same Strings", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/program-to-check-if-two-strings-are-same-or-not/", pattern: "Easy String", level: "Level 1" },
      { id: "CORE-042-02", name: "Multiply Large Numbers", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/multiply-large-numbers-represented-as-strings/", pattern: "Medium String", level: "Level 1" },
      { id: "CORE-042-03", name: "URLify", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/urlify-a-given-string-replace-spaces/", pattern: "Medium String", level: "Level 1" },
      { id: "CORE-042-04", name: "Palindrome", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/palindrome-string/", pattern: "Easy String", level: "Level 1" },
      { id: "CORE-042-05", name: "Smallest string starting from Leaf", difficulty: "Easy", platform: "LeetCode", link: "https://leetcode.com/problems/smallest-string-starting-from-leaf", pattern: "Root-to-Leaf Path", level: "Level 1" },
      { id: "CORE-042-06", name: "Manacher's Algorithm", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/manachers-algorithm-linear-time-longest-palindromic-substring-part-1/", pattern: "String Manipulation", level: "Level 1" },
      { id: "CORE-042-07", name: "Longest Prefix Suffix", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/longest-prefix-also-suffix/", pattern: "String Manipulation", level: "Level 1" },
    ],
  },
  {
    topicNo: 5,
    topic: "Bit Manipulation",
    subtopics: ["Missing Number", "Power of Two", "Counting Set Bits", "Single Number Variants", "Bitwise Range", "Bitwise Arithmetic", "Bit Masking"],
    problems: [
      { id: "CORE-005-01", name: "Missing Number using XOR", difficulty: "Easy", platform: "LeetCode", link: "https://leetcode.com/problems/missing-number/", pattern: "Bitwise XOR", level: "Level 1" },
      { id: "CORE-005-02", name: "Power of Two", difficulty: "Easy", platform: "LeetCode", link: "https://leetcode.com/problems/power-of-two/", pattern: "Bit Manipulation", level: "Level 1" },
      { id: "CORE-005-03", name: "Number of 1 Bits", difficulty: "Easy", platform: "LeetCode", link: "https://leetcode.com/problems/number-of-1-bits/", pattern: "Bit Counting", level: "Level 1" },
      { id: "CORE-005-04", name: "Counting Bits", difficulty: "Easy", platform: "LeetCode", link: "https://leetcode.com/problems/counting-bits/", pattern: "DP + Bit Manipulation", level: "Level 1" },
      { id: "CORE-005-05", name: "Single Number II", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/single-number-ii/", pattern: "Bit Manipulation", level: "Level 2" },
      { id: "CORE-005-06", name: "Bitwise AND of Numbers Range", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/bitwise-and-of-numbers-range/", pattern: "Bit Manipulation", level: "Level 2" },
      { id: "CORE-005-07", name: "Sum of Two Integers", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/sum-of-two-integers/", pattern: "Bitwise Arithmetic", level: "Level 2" },
      { id: "CORE-005-08", name: "Subsets", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/subsets/", pattern: "Bit Masking", level: "Level 2" },
    ],
  },
  {
    topicNo: 6,
    topic: "Hashing",
    subtopics: ["Hashing", "Hashing for Frequency"],
    problems: [
      { id: "CORE-006-01", name: "Roman to Integer", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/roman-number-to-integer/", pattern: "Hashing", level: "Level 1" },
      { id: "CORE-006-02", name: "Separate Chaining", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/c-program-hashing-chaining/", pattern: "Hashing", level: "Level 1" },
      { id: "CORE-006-03", name: "Anagrams", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/check-whether-two-strings-are-anagram-of-each-other/", pattern: "Hashing for Frequency", level: "Level 1" },
      { id: "CORE-006-04", name: "Most Frequent", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/frequent-element-array/", pattern: "Hashing for Frequency", level: "Level 1" },
    ],
  },
  {
    topicNo: 7,
    topic: "Linked List — Basics",
    subtopics: ["Fast & Slow Pointer", "Hard", "Linked List Manipulation", "LinkedList In-place Reversal", "Reversal Pattern", "Sorting & Merging Pattern"],
    problems: [
      { id: "CORE-007-01", name: "Linked List Cycle", difficulty: "Easy", platform: "LeetCode", link: "https://leetcode.com/problems/linked-list-cycle/", pattern: "Fast & Slow Pointer", level: "Level 1" },
      { id: "CORE-007-02", name: "Linked List Cycle II", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/linked-list-cycle-ii/", pattern: "Fast & Slow Pointer", level: "Level 1" },
      { id: "CORE-007-03", name: "Clone with Random Pointer", difficulty: "Hard", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/a-linked-list-with-next-and-arbit-pointer/", pattern: "Hard", level: "Level 1" },
      { id: "CORE-007-04", name: "Flattening", difficulty: "Hard", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/flatten-a-multi-level-linked-list-set-2-depth-wise/", pattern: "Hard", level: "Level 1" },
      { id: "CORE-007-05", name: "Linked-list", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/introduction-to-linked-list-data-structure/", pattern: "Linked List Manipulation", level: "Level 1" },
      { id: "CORE-007-06", name: "Singly", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/singly-linked-list-tutorial/", pattern: "Linked List Manipulation", level: "Level 1" },
      { id: "CORE-007-07", name: "Reverse Linked List", difficulty: "Easy", platform: "LeetCode", link: "https://leetcode.com/problems/reverse-linked-list/", pattern: "LinkedList In-place Reversal", level: "Level 1" },
      { id: "CORE-007-08", name: "Reverse Linked List II", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/reverse-linked-list-ii/", pattern: "LinkedList In-place Reversal", level: "Level 1" },
      { id: "CORE-007-09", name: "Reverse a Doubly", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/reverse-a-doubly-linked-list/", pattern: "Reversal Pattern", level: "Level 1" },
      { id: "CORE-007-10", name: "Reverse in Groups (K-group reversal)", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/reverse-a-linked-list-in-groups-of-given-size/", pattern: "Reversal Pattern", level: "Level 1" },
      { id: "CORE-007-11", name: "Add Two Numbers", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/add-two-numbers-represented-by-linked-list/", pattern: "Sorting & Merging Pattern", level: "Level 1" },
      { id: "CORE-007-12", name: "Sort 0s, 1s, 2s", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/sort-linked-list-0s-1s-2s-changing-links/", pattern: "Sorting & Merging Pattern", level: "Level 1" },
    ],
  },
  {
    topicNo: 8,
    topic: "Stack — Basics",
    subtopics: ["Parentheses", "Min Stack", "Queue Using Stack", "Stack Implementation"],
    problems: [
      { id: "CORE-008-01", name: "Valid Parentheses", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/problems/parenthesis-checker2744/1", pattern: "Stack", level: "Level 1" },
      { id: "CORE-008-02", name: "Min Stack", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/problems/get-min-at-pop/1", pattern: "Stack", level: "Level 1" },
      { id: "CORE-008-03", name: "Implement Queue using Stacks", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/queue-using-stacks/", pattern: "Stack / Queue", level: "Level 1" },
      { id: "CORE-008-04", name: "Implement Stack using Linked List", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/problems/implement-stack-using-linked-list/1", pattern: "Stack", level: "Level 1" },
    ],
  },
  {
    topicNo: 9,
    topic: "Queue / Deque — Basics",
    subtopics: ["Stack Using Queue", "Circular Queue"],
    problems: [
      { id: "CORE-009-01", name: "Implement Stack using Queues", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/implement-stack-using-queue/", pattern: "Queue / Stack", level: "Level 1" },
      { id: "CORE-009-02", name: "Design Circular Queue", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/introduction-to-circular-queue/", pattern: "Queue", level: "Level 1" },
    ],
  },
  {
    topicNo: 10,
    topic: "Recursion — Basics",
    subtopics: ["Factorial", "Array Recursion", "String Recursion"],
    problems: [
      { id: "CORE-010-01", name: "Factorial of a Number", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/problems/factorial5739/1", pattern: "Recursion", level: "Level 1" },
      { id: "CORE-010-02", name: "Check if Array is Sorted", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/check-if-an-array-is-sorted/", pattern: "Recursion", level: "Level 1" },
      { id: "CORE-010-03", name: "Reverse a String", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/reverse-a-string/", pattern: "Recursion / String", level: "Level 1" },
    ],
  },
  {
    topicNo: 11,
    topic: "Arrays — Core Patterns",
    subtopics: ["Bit + Arrays", "Kadane's Algorithm", "Majority Element", "Majority Element II", "Next Permutation", "XOR Array Problems"],
    problems: [
      { id: "CORE-011-01", name: "Max Consecutive 1s", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/maximum-consecutive-ones-or-zeros-in-a-binary-array/", pattern: "Bit + Arrays", level: "Level 2" },
      { id: "CORE-011-02", name: "Missing", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/find-the-missing-number/", pattern: "Bit + Arrays", level: "Level 2" },
      { id: "CORE-011-03", name: "Maximum Subarray", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/maximum-subarray/", pattern: "Kadane's Algorithm", level: "Level 2" },
      { id: "CORE-011-04", name: "Majority Element", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/majority-element/", pattern: "Boyer-Moore Voting", level: "Level 2" },
      { id: "CORE-011-05", name: "Majority Element II", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/majority-element-ii/", pattern: "Extended Boyer-Moore", level: "Level 2" },
      { id: "CORE-011-06", name: "Next Permutation", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/next-permutation/", pattern: "Lexicographic Permutation", level: "Level 2" },
      { id: "CORE-011-07", name: "Single Number", difficulty: "Easy", platform: "LeetCode", link: "https://leetcode.com/problems/single-number/", pattern: "Bitwise XOR", level: "Level 2" },
    ],
  },
  {
    topicNo: 12,
    topic: "Two Pointers",
    subtopics: ["Sorted Array", "Two Pointers", "3Sum", "Container With Most Water"],
    problems: [
      { id: "CORE-012-01", name: "Two Sum II - Sorted Array", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/", pattern: "Two Pointers", level: "Level 2" },
      { id: "CORE-012-02", name: "Sort Colors", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/sort-colors/", pattern: "Two Pointers", level: "Level 2" },
      { id: "CORE-012-03", name: "Two Sum II - Input Array Is Sorted", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/", pattern: "Two Pointers", level: "Level 2" },
      { id: "CORE-012-04", name: "3Sum", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/3sum/", pattern: "Two Pointers + Sorting", level: "Level 2" },
      { id: "CORE-012-05", name: "Container With Most Water", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/container-with-most-water/", pattern: "Opposite Direction", level: "Level 2" },
    ],
  },
  {
    topicNo: 13,
    topic: "Sliding Window",
    subtopics: ["Count Subarrays", "Fixed Sliding Window", "Hard", "Longest Substring", "Minimum Window", "Minimum length", "Sliding Window + Hashing", "Two Heaps", "Variable Sliding Window"],
    problems: [
      { id: "CORE-013-01", name: "Subarrays Less Than K", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/number-subarrays-product-less-k/", pattern: "Count Subarrays", level: "Level 2" },
      { id: "CORE-013-02", name: "Subarrays with k odds", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/number-subarrays-m-odd-numbers/", pattern: "Count Subarrays", level: "Level 2" },
      { id: "CORE-013-03", name: "First negative in every window", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/first-negative-integer-every-window-size-k/", pattern: "Fixed Sliding Window", level: "Level 2" },
      { id: "CORE-013-04", name: "Min Swaps to group all 1's", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/minimum-swaps-required-group-1s-together/", pattern: "Fixed Sliding Window", level: "Level 2" },
      { id: "CORE-013-05", name: "Number of Subarrays having Average Greater or Equal to Threshold", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/number-of-sub-arrays-of-size-k-and-average-greater-than-or-equal-to-threshold/", pattern: "Fixed Sliding Window", level: "Level 2" },
      { id: "CORE-013-06", name: "Repeated DNA sequences", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/repeated-dna-sequences/", pattern: "Fixed Sliding Window", level: "Level 2" },
      { id: "CORE-013-07", name: "Sliding Window Maximum", difficulty: "Hard", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/sliding-window-maximum-maximum-of-all-subarrays-of-size-k/", pattern: "Hard", level: "Level 2" },
      { id: "CORE-013-08", name: "Longest Substring Without Repeating Characters", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/longest-substring-without-repeating-characters/", pattern: "Sliding Window", level: "Level 2" },
      { id: "CORE-013-09", name: "Minimum Window Substring", difficulty: "Hard", platform: "LeetCode", link: "https://leetcode.com/problems/minimum-window-substring/", pattern: "Sliding Window", level: "Level 2" },
      { id: "CORE-013-10", name: "Minimum Window Subsequence", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/minimum-window-subsequence/", pattern: "Minimum length", level: "Level 2" },
      { id: "CORE-013-11", name: "Smallest containing 0, 1 and 2", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/smallest-window-containing-0-1-and-2/", pattern: "Minimum length", level: "Level 2" },
      { id: "CORE-013-12", name: "Count Anagrams", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/count-occurrences-of-anagrams/", pattern: "Sliding Window + Hashing", level: "Level 2" },
      { id: "CORE-013-13", name: "Full Distinct Subarrays", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/count-of-subarrays-having-exactly-k-distinct-elements/", pattern: "Sliding Window + Hashing", level: "Level 2" },
      { id: "CORE-013-14", name: "Sliding Window Median", difficulty: "Hard", platform: "LeetCode", link: "https://leetcode.com/problems/sliding-window-median/", pattern: "Two Heaps", level: "Level 2" },
      { id: "CORE-013-15", name: "Max Consecutive Ones", difficulty: "Hard", platform: "LeetCode", link: "https://leetcode.com/problems/max-consecutive-ones-iii/", pattern: "Variable Sliding Window", level: "Level 2" },
      { id: "CORE-013-16", name: "Maximize Ones", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/find-zeroes-to-be-flipped-so-that-number-of-consecutive-1s-is-maximized/", pattern: "Variable Sliding Window", level: "Level 2" },
      { id: "CORE-013-17", name: "Subarray with given sum", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/find-subarray-with-given-sum/", pattern: "Variable Sliding Window", level: "Level 2" },
      { id: "CORE-013-18", name: "Subarray Product Less Than K", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/subarray-product-less-than-k/", pattern: "Variable Sliding Window", level: "Level 2" },
    ],
  },
  {
    topicNo: 14,
    topic: "Prefix Sum",
    subtopics: ["Difference Array", "Prefix / Suffix", "Prefix Sum"],
    problems: [
      { id: "CORE-014-01", name: "Compute before Matrix", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/compute-before-matrix/", pattern: "Difference Array", level: "Level 2" },
      { id: "CORE-014-02", name: "Point Counts from Intervals", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/computing-point-counts-from-a-set-of-intervals/", pattern: "Difference Array", level: "Level 2" },
      { id: "CORE-014-03", name: "Longest Span", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/longest-span-sum-two-binary-arrays/", pattern: "Prefix / Suffix Transformation", level: "Level 2" },
      { id: "CORE-014-04", name: "Original Array", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/find-original-array-from-given-prefix-sum-array/", pattern: "Prefix / Suffix Transformation", level: "Level 2" },
      { id: "CORE-014-05", name: "Largest with sum divisible by k", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/longest-subarray-sum-divisible-k/", pattern: "Prefix Sum + Hashing", level: "Level 2" },
      { id: "CORE-014-06", name: "Longest with Sum K", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/longest-sub-array-sum-k/", pattern: "Prefix Sum + Hashing", level: "Level 2" },
      { id: "CORE-014-07", name: "Product of Array Except Self", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/product-of-array-except-self/", pattern: "Prefix Sum", level: "Level 2" },
    ],
  },
  {
    topicNo: 15,
    topic: "Binary Search",
    subtopics: ["Binary Search", "Binary Search Tree", "Binary Tree Traversal", "Construction", "Property", "Subsets", "Traversal"],
    problems: [
      { id: "CORE-015-01", name: "First Bad Version", difficulty: "Easy", platform: "LeetCode", link: "https://leetcode.com/problems/first-bad-version/", pattern: "Binary Search", level: "Level 2" },
      { id: "CORE-015-02", name: "Sqrt(x)", difficulty: "Easy", platform: "LeetCode", link: "https://leetcode.com/problems/sqrt-x/", pattern: "Binary Search", level: "Level 2" },
      { id: "CORE-015-03", name: "Insert into a BST", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/insert-into-a-binary-search-tree/", pattern: "Binary Search Tree", level: "Level 2" },
      { id: "CORE-015-04", name: "LCA of BST", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/", pattern: "Binary Search Tree", level: "Level 2" },
      { id: "CORE-015-05", name: "Validate Binary Search Tree", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/validate-binary-search-tree/", pattern: "Binary Tree Traversal", level: "Level 2" },
      { id: "CORE-015-06", name: "Merge two BSTs", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/merge-two-bsts-with-limited-extra-space/", pattern: "Construction", level: "Level 2" },
      { id: "CORE-015-07", name: "Sorted Array to BST", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/sorted-array-to-balanced-bst/", pattern: "Construction", level: "Level 2" },
      { id: "CORE-015-08", name: "Recover BST", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/fix-two-swapped-nodes-of-bst/", pattern: "Property", level: "Level 2" },
      { id: "CORE-015-09", name: "Validate BST", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/a-program-to-check-if-a-binary-tree-is-bst-or-not/", pattern: "Property", level: "Level 2" },
      { id: "CORE-015-10", name: "Count of Structurally Unique Binary Search Trees", difficulty: "Hard", platform: "LeetCode", link: "https://leetcode.com/problems/unique-binary-search-trees/", pattern: "Subsets", level: "Level 2" },
      { id: "CORE-015-11", name: "Structurally Unique Binary Search Trees", difficulty: "Hard", platform: "LeetCode", link: "https://leetcode.com/problems/unique-binary-search-trees-ii/", pattern: "Subsets", level: "Level 2" },
      { id: "CORE-015-12", name: "2 Sum in BST", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/find-pair-given-sum-bst/", pattern: "Traversal", level: "Level 2" },
      { id: "CORE-015-13", name: "Kth Smallest Element", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/find-k-th-smallest-element-in-bst-order-statistics-in-bst/", pattern: "Traversal", level: "Level 2" },
    ],
  },
  {
    topicNo: 16,
    topic: "Linked List — Core",
    subtopics: ["Cycle Detection", "Length of Loop", "Reverse in K Groups", "Intersection", "Merge Sorted Lists", "Palindrome"],
    problems: [
      { id: "CORE-016-01", name: "Detect Loop", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/detect-loop-in-a-linked-list/", pattern: "Fast & Slow Pointers", level: "Level 2" },
      { id: "CORE-016-02", name: "Length of the Loop", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/find-length-of-loop-in-linked-list/", pattern: "Fast & Slow Pointers", level: "Level 2" },
      { id: "CORE-016-03", name: "Reverse in groups", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/problems/reverse-a-linked-list-in-groups-of-given-size/1", pattern: "Linked List Reversal", level: "Level 2" },
      { id: "CORE-016-04", name: "Intersection Point", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/write-a-function-to-get-the-intersection-point-of-two-linked-lists/", pattern: "Two Pointers", level: "Level 2" },
      { id: "CORE-016-05", name: "Merge two sorted linked lists", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/merge-two-sorted-linked-lists/", pattern: "Merge", level: "Level 2" },
      { id: "CORE-016-06", name: "Palindrome Linked List", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/function-to-check-if-a-singly-linked-list-is-palindrome/", pattern: "Reverse + Two Pointers", level: "Level 2" },
    ],
  },
  {
    topicNo: 17,
    topic: "Stack",
    subtopics: ["Decode String", "Easy", "Expression", "Stack Applications"],
    problems: [
      { id: "CORE-017-01", name: "Decode String", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/decode-string-recursively-encoded-count-followed-substring/", pattern: "String Simulation", level: "Level 2" },
      { id: "CORE-017-02", name: "Queue using Stacks", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/queue-using-stacks/", pattern: "Easy", level: "Level 2" },
      { id: "CORE-017-03", name: "Longest Valid", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/length-of-the-longest-valid-substring/", pattern: "Expression", level: "Level 2" },
      { id: "CORE-017-04", name: "Score of Balanced", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/calculate-score-of-parentheses-from-a-given-string/", pattern: "Expression", level: "Level 2" },
      { id: "CORE-017-05", name: "Sort", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/sort-a-stack-using-recursion/", pattern: "Stack Applications", level: "Level 2" },
      { id: "CORE-017-06", name: "Stack", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/introduction-to-stack-data-structure-and-algorithm-tutorials/", pattern: "Stack Applications", level: "Level 2" },
    ],
  },
  {
    topicNo: 18,
    topic: "Monotonic Stack",
    subtopics: ["Daily Temperatures", "Next Greater Element", "Largest Rectangle"],
    problems: [
      { id: "CORE-018-01", name: "Daily Temperatures", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/daily-temperatures/", pattern: "Monotonic Stack", level: "Level 2" },
      { id: "CORE-018-02", name: "Next Greater Element II", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/next-greater-element-ii/", pattern: "Monotonic Stack", level: "Level 2" },
      { id: "CORE-018-03", name: "Next Greater Element I", difficulty: "Easy", platform: "LeetCode", link: "https://leetcode.com/problems/next-greater-element-i/", pattern: "Monotonic Stack", level: "Level 2" },
      { id: "CORE-018-04", name: "Largest Rectangle in Histogram", difficulty: "Hard", platform: "LeetCode", link: "https://leetcode.com/problems/largest-rectangle-in-histogram/", pattern: "Monotonic Stack", level: "Level 2" },
    ],
  },
  {
    topicNo: 19,
    topic: "Queue / Deque",
    subtopics: ["Easy", "Hard", "Medium", "Queue / Deque"],
    problems: [
      { id: "CORE-019-01", name: "Circular Queue", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/introduction-to-circular-queue/", pattern: "Easy", level: "Level 2" },
      { id: "CORE-019-02", name: "Longest Subarray with Difference ≤ X", difficulty: "Hard", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/longest-subarray-in-which-absolute-difference-between-any-two-element-is-not-greater-than-x/", pattern: "Hard", level: "Level 2" },
      { id: "CORE-019-03", name: "Max Subarray Length with K Increments", difficulty: "Hard", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/maximize-length-of-subarray-of-equal-elements-by-performing-at-most-k-increment-operations/", pattern: "Hard", level: "Level 2" },
      { id: "CORE-019-04", name: "First non-repeating in a stream", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/find-first-non-repeating-character-stream-characters/", pattern: "Medium", level: "Level 2" },
      { id: "CORE-019-05", name: "Min Knight steps for target", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/minimum-steps-reach-target-knight/", pattern: "Medium", level: "Level 2" },
      { id: "CORE-019-06", name: "Deque", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/deque-data-structure/", pattern: "Queue / Deque", level: "Level 2" },
      { id: "CORE-019-07", name: "Queue", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/introduction-to-queue-data-structure-and-algorithm-tutorials/", pattern: "Queue / Deque", level: "Level 2" },
    ],
  },
  {
    topicNo: 20,
    topic: "Intervals",
    subtopics: ["Meeting Rooms", "Merge Intervals", "Non-overlapping Intervals", "Two Heaps"],
    problems: [
      { id: "CORE-020-01", name: "Meeting Rooms", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/meeting-rooms-check-if-a-person-can-attend-all-meetings/", pattern: "Medium", level: "Level 2" },
      { id: "CORE-020-02", name: "Insert Interval", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/insert-interval/", pattern: "Merge Intervals", level: "Level 2" },
      { id: "CORE-020-03", name: "Merge Intervals", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/merge-intervals/", pattern: "Merge Intervals", level: "Level 2" },
      { id: "CORE-020-04", name: "Non-Overlapping Intervals", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/minimum-removals-required-to-make-ranges-non-overlapping/", pattern: "Medium", level: "Level 2" },
      { id: "CORE-020-05", name: "Next Interval", difficulty: "Hard", platform: "LeetCode", link: "https://leetcode.com/problems/find-right-interval/", pattern: "Two Heaps", level: "Level 2" },
    ],
  },
  {
    topicNo: 21,
    topic: "Greedy",
    subtopics: ["Easy", "Fractional Knapsack", "Hard", "Jump Game", "Medium"],
    problems: [
      { id: "CORE-021-01", name: "Assign Cookies", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/assign-cookies/", pattern: "Easy", level: "Level 2" },
      { id: "CORE-021-02", name: "Fractional Knapsack", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/fractional-knapsack-problem/", pattern: "Easy", level: "Level 2" },
      { id: "CORE-021-03", name: "Min time to finish all jobs with given constraints", difficulty: "Hard", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/find-minimum-time-to-finish-all-jobs-with-given-constraints/", pattern: "Hard", level: "Level 2" },
      { id: "CORE-021-04", name: "Minimize cash flow", difficulty: "Hard", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/minimize-cash-flow-among-given-set-friends-borrowed-money/", pattern: "Hard", level: "Level 2" },
      { id: "CORE-021-05", name: "Jump Game", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/minimum-number-of-jumps-to-reach-end-of-a-given-array/", pattern: "Medium", level: "Level 2" },
      { id: "CORE-021-06", name: "Job Sequencing", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/job-sequencing-problem/", pattern: "Medium", level: "Level 2" },
    ],
  },
  {
    topicNo: 22,
    topic: "Trees — Core",
    subtopics: ["Ancestor problem", "Binary Tree", "Boundary Traversal", "Easy", "Horizontal Distance Based", "Inorder", "Level Order", "Postorder", "Tree Depth First Search (DFS)", "Vertical Traversal"],
    problems: [
      { id: "CORE-022-01", name: "Kth Ancestor of a Tree Node", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/kth-ancestor-of-a-tree-node/", pattern: "Ancestor problem", level: "Level 2" },
      { id: "CORE-022-02", name: "Binary Tree Level Order Traversal", difficulty: "Easy", platform: "LeetCode", link: "https://leetcode.com/problems/binary-tree-level-order-traversal/", pattern: "Binary Tree Traversal", level: "Level 2" },
      { id: "CORE-022-03", name: "Level Averages in a Binary Tree", difficulty: "Easy", platform: "LeetCode", link: "https://leetcode.com/problems/average-of-levels-in-binary-tree/", pattern: "Tree Breadth First Search", level: "Level 2" },
      { id: "CORE-022-04", name: "Binary Tree", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/introduction-to-tree-data-structure/", pattern: "Tree Traversal / Properties", level: "Level 2" },
      { id: "CORE-022-05", name: "All Nodes Distance K in Binary tree", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/all-nodes-distance-k-in-binary-tree/", pattern: "Level Order Traversal (BFS in Binary Tree)", level: "Level 2" },
      { id: "CORE-022-06", name: "Balanced Binary Tree", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/balanced-binary-tree/", pattern: "Height related Problems", level: "Level 2" },
      { id: "CORE-022-07", name: "Binary Tree Paths", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/binary-tree-paths/", pattern: "Root-to-Leaf Path", level: "Level 2" },
      { id: "CORE-022-08", name: "Binary Tree Zigzag Level Order Traversal", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/", pattern: "Binary Tree Traversal", level: "Level 2" },
      { id: "CORE-022-09", name: "Diameter of Binary Tree", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/diameter-of-binary-tree/", pattern: "Height related Problems", level: "Level 2" },
      { id: "CORE-022-10", name: "LCA of Binary Tree", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/", pattern: "Ancestor problem", level: "Level 2" },
      { id: "CORE-022-11", name: "Maximum Depth of Binary Tree", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/maximum-depth-of-binary-tree/", pattern: "DFS", level: "Level 2" },
      { id: "CORE-022-12", name: "Maximum width of Binary Tree", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/maximum-width-of-binary-tree/", pattern: "Level Order Traversal (BFS in Binary Tree)", level: "Level 2" },
      { id: "CORE-022-13", name: "Boundary Traversal", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/problems/boundary-traversal-of-binary-tree/1", pattern: "Medium", level: "Level 2" },
      { id: "CORE-022-14", name: "Max Path Sum", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/find-maximum-path-sum-in-a-binary-tree/", pattern: "Easy", level: "Level 2" },
      { id: "CORE-022-15", name: "Right View", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/print-right-view-binary-tree-2/", pattern: "Easy", level: "Level 2" },
      { id: "CORE-022-16", name: "Bottom View", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/bottom-view-binary-tree/", pattern: "Horizontal Distance Based", level: "Level 2" },
      { id: "CORE-022-17", name: "Morris Inorder", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/inorder-tree-traversal-without-recursion-and-without-stack/", pattern: "Iterative Traversals", level: "Level 2" },
      { id: "CORE-022-18", name: "Tree from Preorder and Inorder", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/construct-tree-from-given-inorder-and-preorder-traversal/", pattern: "Medium", level: "Level 2" },
      { id: "CORE-022-19", name: "Construct BT from Postorder and Inorder", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/", pattern: "Tree Construction", level: "Level 2" },
      { id: "CORE-022-20", name: "Construct BT from Preorder and Inorder", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/", pattern: "Tree Construction", level: "Level 2" },
      { id: "CORE-022-21", name: "Reverse Level Order Traversal", difficulty: "Easy", platform: "LeetCode", link: "https://leetcode.com/problems/binary-tree-level-order-traversal-ii/", pattern: "Tree Breadth First Search", level: "Level 2" },
      { id: "CORE-022-22", name: "Level Order", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/level-order-tree-traversal/", pattern: "Tree Traversal / Properties", level: "Level 2" },
      { id: "CORE-022-23", name: "Postorder", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/iterative-postorder-traversal-using-stack/", pattern: "Iterative Traversals", level: "Level 2" },
      { id: "CORE-022-24", name: "Count Paths for a Sum", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/path-sum-iii/", pattern: "Tree Depth First Search (DFS)", level: "Level 2" },
      { id: "CORE-022-25", name: "Vertical Traversal", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/vertical-order-traversal-of-binary-tree-using-map/", pattern: "Horizontal Distance Based", level: "Level 2" },
    ],
  },
  {
    topicNo: 23,
    topic: "BST",
    subtopics: ["BST from Preorder", "Hard", "String DP"],
    problems: [
      { id: "CORE-023-01", name: "Construct BST from Preorder", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal/", pattern: "Tree Construction", level: "Level 2" },
      { id: "CORE-023-02", name: "Min Repeats for Substring", difficulty: "Hard", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/minimum-number-of-times-a-has-to-be-repeated-such-that-b-is-a-substring-of-it/", pattern: "Hard", level: "Level 2" },
      { id: "CORE-023-03", name: "Palindrome Substring Queries", difficulty: "Hard", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/palindrome-substring-queries/", pattern: "Hard", level: "Level 2" },
      { id: "CORE-023-04", name: "Longest Palindromic Substrings", difficulty: "Easy", platform: "LeetCode", link: "https://leetcode.com/problems/longest-palindromic-substring/", pattern: "String DP", level: "Level 2" },
      { id: "CORE-023-05", name: "Palindromic Substrings", difficulty: "Easy", platform: "LeetCode", link: "https://leetcode.com/problems/palindromic-substrings/", pattern: "String DP", level: "Level 2" },
    ],
  },
  {
    topicNo: 24,
    topic: "Heap / Priority Queue",
    subtopics: ["Easy", "Graph Algorithms", "Heap / Priority Queue", "Kth Largest", "Medium", "Min Heap", "Top K"],
    problems: [
      { id: "CORE-024-01", name: "Check for Heap", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/how-to-check-if-a-given-array-represents-a-binary-heap/", pattern: "Easy", level: "Level 2" },
      { id: "CORE-024-02", name: "Heap Sort", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/heap-sort/", pattern: "Easy", level: "Level 2" },
      { id: "CORE-024-03", name: "Dijkstra's Algorithm: Cheapest Flights Within K Stops", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/cheapest-flights-within-k-stops/", pattern: "Graph Algorithms", level: "Level 2" },
      { id: "CORE-024-04", name: "Heap", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/binary-heap/", pattern: "Heap / Priority Queue", level: "Level 2" },
      { id: "CORE-024-05", name: "Kth Largest Element in an Array", difficulty: "Easy", platform: "LeetCode", link: "https://leetcode.com/problems/kth-largest-element-in-an-array/", pattern: "Top K Elements", level: "Level 2" },
      { id: "CORE-024-06", name: "K Max sum combinations", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/k-maximum-sum-combinations-two-arrays/", pattern: "Medium", level: "Level 2" },
      { id: "CORE-024-07", name: "BST to Min Heap", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/convert-bst-min-heap/", pattern: "Medium", level: "Level 2" },
      { id: "CORE-024-08", name: "Top K Frequent Elements", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/top-k-frequent-elements/", pattern: "Top K Elements", level: "Level 2" },
    ],
  },
  {
    topicNo: 25,
    topic: "Graph Basics",
    subtopics: ["BFS", "DFS"],
    problems: [
      { id: "CORE-025-01", name: "BFS of Graph", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/breadth-first-search-or-bfs-for-a-graph/", pattern: "Graph Traversal", level: "Level 2" },
      { id: "CORE-025-02", name: "DFS of Graph", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/depth-first-search-or-dfs-for-a-graph/", pattern: "Graph Traversal", level: "Level 2" },
    ],
  },
  {
    topicNo: 26,
    topic: "BFS / DFS",
    subtopics: ["Number of Islands", "Flood Fill", "Cycle Detection", "Bipartite Graph"],
    problems: [
      { id: "CORE-026-01", name: "Number of islands", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/find-the-number-of-islands-using-dfs/", pattern: "Grid DFS/BFS", level: "Level 2" },
      { id: "CORE-026-02", name: "Flood Fill Algorithm", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/flood-fill-algorithm/", pattern: "Grid DFS/BFS", level: "Level 2" },
      { id: "CORE-026-03", name: "Detect cycle in an undirected graph", difficulty: "Easy", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/detect-cycle-undirected-graph/", pattern: "DFS / BFS", level: "Level 2" },
      { id: "CORE-026-04", name: "Bipartite Graph", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/bipartite-graph/", pattern: "BFS / DFS Coloring", level: "Level 2" },
    ],
  },
  {
    topicNo: 27,
    topic: "Backtracking",
    subtopics: ["Generate Parentheses", "Hard", "Medium", "Permutations", "Subsets", "Word Search"],
    problems: [
      { id: "CORE-027-01", name: "Generate Parentheses", difficulty: "Hard", platform: "LeetCode", link: "https://leetcode.com/problems/generate-parentheses/", pattern: "Backtracking", level: "Level 2" },
      { id: "CORE-027-02", name: "Knight's Tour", difficulty: "Hard", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/the-knights-tour-problem/", pattern: "Hard", level: "Level 2" },
      { id: "CORE-027-03", name: "N Queen Problem", difficulty: "Hard", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/n-queen-problem-backtracking-3/", pattern: "Hard", level: "Level 2" },
      { id: "CORE-027-04", name: "Rat in a Maze", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/rat-in-a-maze/", pattern: "Medium", level: "Level 2" },
      { id: "CORE-027-05", name: "Permutations", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/permutations/", pattern: "Backtracking", level: "Level 2" },
      { id: "CORE-027-06", name: "Unique Generalized Abbreviations", difficulty: "Hard", platform: "LeetCode", link: "https://leetcode.com/problems/generalized-abbreviation/", pattern: "Subsets", level: "Level 2" },
      { id: "CORE-027-07", name: "Max Subsets", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/minimum-number-subsets-distinct-elements/", pattern: "Hashing for Frequency", level: "Level 2" },
      { id: "CORE-027-08", name: "Subsets With Duplicates", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/subsets-ii/", pattern: "Subsets", level: "Level 2" },
      { id: "CORE-027-09", name: "Word Search", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/check-if-a-word-exists-in-a-grid-or-not/", pattern: "Medium", level: "Level 2" },
    ],
  },
  {
    topicNo: 28,
    topic: "Advanced Array Patterns",
    subtopics: ["Circular Subarray", "Trapping Rain Water", "Smallest Missing Positive"],
    problems: [
      { id: "CORE-028-01", name: "Maximum Circular Subarray Sum", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/maximum-contiguous-circular-sum/", pattern: "Kadane's Algorithm", level: "Level 3" },
      { id: "CORE-028-02", name: "Trapping Rain Water", difficulty: "Hard", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/trapping-rain-water/", pattern: "Two Pointers", level: "Level 3" },
      { id: "CORE-028-03", name: "Smallest Missing Positive Number", difficulty: "Hard", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/find-the-smallest-positive-number-missing-from-an-unsorted-array/", pattern: "Cyclic Sort / Index Placement", level: "Level 3" },
    ],
  },
  {
    topicNo: 29,
    topic: "Advanced Binary Search",
    subtopics: ["Modified Binary Search", "Search on Answer"],
    problems: [
      { id: "CORE-029-01", name: "Minimum Number of Days to Make m Bouquets", difficulty: "Hard", platform: "LeetCode", link: "https://leetcode.com/problems/minimum-number-of-days-to-make-m-bouquets/", pattern: "Modified Binary Search", level: "Level 3" },
      { id: "CORE-029-02", name: "Search in Rotated Sorted Array", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/search-in-rotated-sorted-array/", pattern: "Modified Binary Search", level: "Level 3" },
      { id: "CORE-029-03", name: "M bouquets", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/minimum-days-to-make-m-bouquets/", pattern: "Binary Search on Answer", level: "Level 3" },
      { id: "CORE-029-04", name: "kth in Multiplication Table", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/kth-smallest-number-in-multiplication-table/", pattern: "Binary Search on Answer", level: "Level 3" },
    ],
  },
  {
    topicNo: 30,
    topic: "Advanced Linked List",
    subtopics: ["LinkedList In-place Reversal"],
    problems: [
      { id: "CORE-030-01", name: "Reverse Nodes in k-Group", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/reverse-nodes-in-k-group/", pattern: "LinkedList In-place Reversal", level: "Level 3" },
      { id: "CORE-030-02", name: "Rotate List", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/rotate-list/", pattern: "LinkedList In-place Reversal", level: "Level 3" },
    ],
  },
  {
    topicNo: 31,
    topic: "Advanced Trees",
    subtopics: ["Hard", "MST/DSU", "Maximum Path Sum", "Topological Sort"],
    problems: [
      { id: "CORE-031-01", name: "LCA", difficulty: "Hard", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/lowest-common-ancestor-binary-tree-set-1/", pattern: "Hard", level: "Level 3" },
      { id: "CORE-031-02", name: "Spiral Level Order", difficulty: "Hard", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/level-order-traversal-in-spiral-form/", pattern: "Hard", level: "Level 3" },
      { id: "CORE-031-03", name: "Total Spanning Trees", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/total-number-spanning-trees-graph/", pattern: "MST/DSU", level: "Level 3" },
      { id: "CORE-031-04", name: "Binary Tree Maximum Path Sum", difficulty: "Hard", platform: "LeetCode", link: "https://leetcode.com/problems/binary-tree-maximum-path-sum/", pattern: "Root-to-Leaf Path", level: "Level 3" },
      { id: "CORE-031-05", name: "Minimum Height Trees", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/minimum-height-trees/", pattern: "Topological Sort", level: "Level 3" },
    ],
  },
  {
    topicNo: 32,
    topic: "Advanced BST",
    subtopics: ["Implementation", "String"],
    problems: [
      { id: "CORE-032-01", name: "Count of distinct substrings", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/count-number-of-distinct-substring-in-a-string/", pattern: "Implementation", level: "Level 3" },
      { id: "CORE-032-02", name: "Longest Common Substring", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/longest-common-substring-dp-29/", pattern: "String", level: "Level 3" },
    ],
  },
  {
    topicNo: 33,
    topic: "Advanced Heap Patterns",
    subtopics: ["Hard", "K-way Merge", "Two Heaps"],
    problems: [
      { id: "CORE-033-01", name: "Sort by Frequency", difficulty: "Hard", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/sort-elements-by-frequency/", pattern: "Hard", level: "Level 3" },
      { id: "CORE-033-02", name: "The Skyline Problem", difficulty: "Hard", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/the-skyline-problem-using-divide-and-conquer-algorithm/", pattern: "Hard", level: "Level 3" },
      { id: "CORE-033-03", name: "Smallest Range: Smallest Range Covering Elements from K Lists", difficulty: "Hard", platform: "LeetCode", link: "https://leetcode.com/problems/smallest-range-covering-elements-from-k-lists/", pattern: "K-way Merge", level: "Level 3" },
      { id: "CORE-033-04", name: "Find K Pairs with Smallest Sums", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/find-k-pairs-with-smallest-sums/", pattern: "K-way Merge", level: "Level 3" },
      { id: "CORE-033-05", name: "IPO", difficulty: "Hard", platform: "LeetCode", link: "https://leetcode.com/problems/ipo/", pattern: "Two Heaps", level: "Level 3" },
    ],
  },
  {
    topicNo: 34,
    topic: "Shortest Path",
    subtopics: ["BFS", "Floyd-Warshall", "Network Delay", "Shortest Path", "Word Ladder", "Knight Moves"],
    problems: [
      { id: "CORE-034-01", name: "Shortest Path in Binary Matrix", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/shortest-path-in-binary-matrix/", pattern: "BFS", level: "Level 3" },
      { id: "CORE-034-02", name: "Floyd-Warshall: Find the City with Smallest Number of Neighbours at a Threshold Distance", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/", pattern: "Graph Algorithms", level: "Level 3" },
      { id: "CORE-034-03", name: "Bellman Ford: Network Delay time", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/network-delay-time", pattern: "Graph Algorithms", level: "Level 3" },
      { id: "CORE-034-04", name: "Shortest cycle in an undirected graph", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/shortest-cycle-in-an-undirected-unweighted-graph/", pattern: "Shortest Path", level: "Level 3" },
      { id: "CORE-034-05", name: "Shortest path with one curved edge in an undirected Graph", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/shortest-path-with-one-curved-edge-in-an-undirected-graph/", pattern: "Shortest Path", level: "Level 3" },
      { id: "CORE-034-06", name: "Word Ladder", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/word-ladder/", pattern: "BFS", level: "Level 3" },
      { id: "CORE-034-07", name: "Steps by Knight", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/minimum-steps-reach-target-knight/", pattern: "BFS Shortest Path", level: "Level 3" },
    ],
  },
  {
    topicNo: 35,
    topic: "Topological Sort / DAG",
    subtopics: ["Alien Dictionary", "Course Schedule", "Topological Sort", "Kahn's Algorithm"],
    problems: [
      { id: "CORE-035-01", name: "Alien Dictionary", difficulty: "Hard", platform: "LeetCode", link: "https://leetcode.com/problems/alien-dictionary/", pattern: "Topological Sort", level: "Level 3" },
      { id: "CORE-035-02", name: "Course Schedule", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/course-schedule/", pattern: "DFS", level: "Level 3" },
      { id: "CORE-035-03", name: "Sequence Reconstruction", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/sequence-reconstruction/", pattern: "Topological Sort", level: "Level 3" },
      { id: "CORE-035-04", name: "Topological Sort", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/topological-sorting/", pattern: "Kahn's Algorithm", level: "Level 3" },
    ],
  },
  {
    topicNo: 36,
    topic: "DSU / Union-Find",
    subtopics: ["Graph Algorithms", "Hashing", "MST/DSU", "Merge & Merge Sort Based", "Union Find (Disjoint Set)"],
    problems: [
      { id: "CORE-036-01", name: "Kruskal's Algorithm: Minimum Cost to connect all Points", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/min-cost-to-connect-all-points/", pattern: "Graph Algorithms", level: "Level 3" },
      { id: "CORE-036-02", name: "Union", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/union-of-two-arrays/", pattern: "Hashing", level: "Level 3" },
      { id: "CORE-036-03", name: "Detect Cycle using DSU", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/detect-cycle-in-graph-using-dsu/", pattern: "MST/DSU", level: "Level 3" },
      { id: "CORE-036-04", name: "Number of connected components", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/number-of-connected-components-of-a-graph-using-disjoint-set-union/", pattern: "MST/DSU", level: "Level 3" },
      { id: "CORE-036-05", name: "Union of 2 Sorted", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/union-of-two-sorted-arrays/", pattern: "Merge & Merge Sort Based", level: "Level 3" },
      { id: "CORE-036-06", name: "Number of Operations to Make Network Connected", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/number-of-operations-to-make-network-connected/", pattern: "Union Find (Disjoint Set)", level: "Level 3" },
      { id: "CORE-036-07", name: "Redundant Connection", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/redundant-connection/", pattern: "Union Find (Disjoint Set)", level: "Level 3" },
    ],
  },
  {
    topicNo: 37,
    topic: "Minimum Spanning Tree",
    subtopics: ["Kruskal", "Prim", "MST + DSU"],
    problems: [
      { id: "CORE-037-01", name: "Kruskal's Minimum Spanning Tree", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/kruskals-minimum-spanning-tree-algorithm-greedy-algo-2/", pattern: "MST + DSU", level: "Level 3" },
      { id: "CORE-037-02", name: "Prim's Minimum Spanning Tree", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/prims-minimum-spanning-tree-mst-greedy-algo-5/", pattern: "MST + Heap", level: "Level 3" },
      { id: "CORE-037-03", name: "Minimum Cost to Connect Points", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/min-cost-to-connect-all-points/", pattern: "MST", level: "Level 3" },
    ],
  },
  {
    topicNo: 38,
    topic: "Trie",
    subtopics: ["Advanced Trie Application", "Implementation", "Search", "Trie Construction", "Prefix Search"],
    problems: [
      { id: "CORE-038-01", name: "Palindrome Pairs", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/palindrome-pair-in-an-array-of-words-or-strings/", pattern: "Advanced Trie Application", level: "Level 3" },
      { id: "CORE-038-02", name: "Longest Word With All Prefixes", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/longest-valid-word-with-all-prefixes/", pattern: "Implementation", level: "Level 3" },
      { id: "CORE-038-03", name: "Search Suggestions System", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/auto-complete-feature-using-trie/", pattern: "Advanced Trie Application", level: "Level 3" },
      { id: "CORE-038-04", name: "Implement Trie (Prefix Tree)", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/implement-trie-prefix-tree/", pattern: "Trie", level: "Level 3" },
      { id: "CORE-038-05", name: "Implement Trie II (Prefix Tree)", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/implement-trie-ii-prefix-tree/", pattern: "Trie / Prefix Counting", level: "Level 3" },
    ],
  },
  {
    topicNo: 39,
    topic: "Matrix / Grid",
    subtopics: ["2-D DP", "2D Array", "Grid", "Grid DP", "Matrix / Grid", "Matrix Manipulation", "Matrix Traversal", "Partition", "Set Matrix Zeroes", "Surrounded Regions"],
    problems: [
      { id: "CORE-039-01", name: "Largest Square Submatrix with All 1s", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/maximum-size-sub-matrix-with-all-1s-in-a-binary-matrix/", pattern: "2-D DP", level: "Level 3" },
      { id: "CORE-039-02", name: "Queries in a Matrix", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/queries-in-a-matrix/", pattern: "2D Array", level: "Level 3" },
      { id: "CORE-039-03", name: "Set Matrix 0", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/set-matrix-rows-and-columns-to-zeroes/", pattern: "2D Array", level: "Level 3" },
      { id: "CORE-039-04", name: "Longest Increasing Path", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/longest-increasing-path-matrix/", pattern: "Grid", level: "Level 3" },
      { id: "CORE-039-05", name: "Maximum path sum in matrix", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/find-the-longest-path-in-a-matrix-with-given-constraints/", pattern: "Grid", level: "Level 3" },
      { id: "CORE-039-06", name: "Dungeon Game: Dungeon Game", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/dungeon-game/", pattern: "Grid DP", level: "Level 3" },
      { id: "CORE-039-07", name: "Maximal Square", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/maximal-square/", pattern: "Grid DP", level: "Level 3" },
      { id: "CORE-039-08", name: "Matrix", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/introduction-to-matrix-or-grid-data-structure-and-algorithms-tutorial/", pattern: "Matrix / Grid", level: "Level 3" },
      { id: "CORE-039-09", name: "Game of Life", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/game-of-life/", pattern: "Matrix Manipulation", level: "Level 3" },
      { id: "CORE-039-10", name: "Max Area of Island", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/max-area-of-island/", pattern: "Matrix Traversal", level: "Level 3" },
      { id: "CORE-039-11", name: "Number of Closed Islands", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/number-of-closed-islands/", pattern: "Matrix Traversal", level: "Level 3" },
      { id: "CORE-039-12", name: "Matrix Chain Multiplication", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/matrix-chain-multiplication-dp-8/", pattern: "Partition", level: "Level 3" },
      { id: "CORE-039-13", name: "Set Matrix Zeroes", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/set-matrix-zeroes/", pattern: "Matrix Manipulation", level: "Level 3" },
      { id: "CORE-039-14", name: "Surrounded Regions", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/surrounded-regions/", pattern: "Matrix Traversal", level: "Level 3" },
    ],
  },
  {
    topicNo: 40,
    topic: "Dynamic Programming — Core",
    subtopics: ["1-D DP", "2-D DP", "Coin Change", "DP", "DP on Stocks", "Fibonacci", "House Robber", "Stock", "String", "Take / Not Take"],
    problems: [
      { id: "CORE-040-01", name: "Derangements", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/count-derangements-permutation-such-that-no-element-appears-in-its-original-position/", pattern: "1-D DP", level: "Level 3" },
      { id: "CORE-040-02", name: "Possible Decodings", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/count-possible-decodings-given-digit-sequence/", pattern: "1-D DP", level: "Level 3" },
      { id: "CORE-040-03", name: "Minimum cost Path", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/min-cost-path-dp-6/", pattern: "2-D DP", level: "Level 3" },
      { id: "CORE-040-04", name: "Coin Change", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/coin-change/", pattern: "Dynamic Programming", level: "Level 3" },
      { id: "CORE-040-05", name: "Dynamic Programming", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/introduction-to-dynamic-programming-data-structures-and-algorithm-tutorials/", pattern: "DP", level: "Level 3" },
      { id: "CORE-040-06", name: "Buy and Sell Stocks iii", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/", pattern: "DP on Stocks", level: "Level 3" },
      { id: "CORE-040-07", name: "Buy and Sell Stocks iv", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/", pattern: "DP on Stocks", level: "Level 3" },
      { id: "CORE-040-08", name: "Fibonacci Number", difficulty: "Easy", platform: "LeetCode", link: "https://leetcode.com/problems/fibonacci-number/", pattern: "Dynamic Programming (1D & 2D)", level: "Level 3" },
      { id: "CORE-040-09", name: "House Robber ii", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/house-robber-ii/", pattern: "Take / Not Take DP", level: "Level 3" },
      { id: "CORE-040-10", name: "Buy and Sell - k Transactions", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/maximum-profit-by-buying-and-selling-a-share-at-most-k-times/", pattern: "Stock", level: "Level 3" },
      { id: "CORE-040-11", name: "Buy and Sell with Transaction Fee", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/maximum-profit-after-buying-and-selling-the-stocks-with-transaction-fees/", pattern: "Stock", level: "Level 3" },
      { id: "CORE-040-12", name: "Interleaving String", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/find-if-a-string-is-interleaved-of-two-other-strings-dp-33/", pattern: "String", level: "Level 3" },
      { id: "CORE-040-13", name: "Target Sum", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/target-sum/", pattern: "Take / Not Take DP", level: "Level 3" },
    ],
  },
  {
    topicNo: 41,
    topic: "DP Patterns",
    subtopics: ["0/1 Knapsack", "Dynamic Programming", "Easy String", "Infinite Supply", "LIS", "Medium Array", "Partition", "Partition DP", "String DP", "SubSequence", "Subsequence"],
    problems: [
      { id: "CORE-041-01", name: "0/1 Knapsack", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/0-1-knapsack-problem-dp-10/", pattern: "SubSequence", level: "Level 3" },
      { id: "CORE-041-02", name: "Longest Common Subsequence", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/longest-common-subsequence/", pattern: "Dynamic Programming", level: "Level 3" },
      { id: "CORE-041-03", name: "Check Subsequence", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/given-two-strings-find-first-string-subsequence-second/", pattern: "Easy String", level: "Level 3" },
      { id: "CORE-041-04", name: "Coin Change II", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/coin-change-ii/", pattern: "Infinite Supply DP", level: "Level 3" },
      { id: "CORE-041-05", name: "Minimum Cost For Tickets", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/minimum-cost-for-tickets/", pattern: "Infinite Supply DP", level: "Level 3" },
      { id: "CORE-041-06", name: "Perfect Squares", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/perfect-squares/", pattern: "Infinite Supply DP", level: "Level 3" },
      { id: "CORE-041-07", name: "Maximum Length of Pair Chain", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/maximum-length-of-pair-chain/", pattern: "LIS", level: "Level 3" },
      { id: "CORE-041-08", name: "Number of LIS", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/number-of-longest-increasing-subsequence/", pattern: "LIS", level: "Level 3" },
      { id: "CORE-041-09", name: "Sorted subsequence of 3", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/find-a-sorted-subsequence-of-size-3-in-linear-time/", pattern: "Medium Array", level: "Level 3" },
      { id: "CORE-041-10", name: "Boolean Parenthesization", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/boolean-parenthesization-problem-dp-37/", pattern: "Partition", level: "Level 3" },
      { id: "CORE-041-11", name: "Optimal Strategy", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/optimal-strategy-for-a-game-dp-31/", pattern: "Partition", level: "Level 3" },
      { id: "CORE-041-12", name: "Burst Balloons", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/burst-balloons/", pattern: "Partition DP", level: "Level 3" },
      { id: "CORE-041-13", name: "Minimum Cost to Cut a Stick", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/minimum-cost-to-cut-a-stick/", pattern: "Partition DP", level: "Level 3" },
      { id: "CORE-041-14", name: "Longest Palindromic Subsequence", difficulty: "Medium", platform: "LeetCode", link: "https://leetcode.com/problems/longest-palindromic-subsequence/", pattern: "String DP", level: "Level 3" },
      { id: "CORE-041-15", name: "Rod Cutting", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/cutting-a-rod-dp-13/", pattern: "SubSequence", level: "Level 3" },
      { id: "CORE-041-16", name: "Consecutive Subsequence", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/count-minimum-number-subsets-subsequences-consecutive-numbers/", pattern: "Subsequence", level: "Level 3" },
      { id: "CORE-041-17", name: "Longest Consecutive Subsequence", difficulty: "Medium", platform: "GeeksforGeeks", link: "https://www.geeksforgeeks.org/dsa/longest-consecutive-subsequence/", pattern: "Subsequence", level: "Level 3" },
    ],
  },
];

export const CORE_PROBLEM_COUNT = CORE_SECTIONS.reduce((a, s) => a + s.problems.length, 0);

