/**
 * NEW FILE (Upgrade 1)
 *
 * Curated, hand-verified canonical problem URLs, keyed by the exact `n` (name)
 * used in `a2z-data.ts`.
 *
 * RULE: only add an entry here when the canonical URL is known with certainty.
 * Anything missing from this map keeps the existing search-URL fallback in
 * `platformLink()` and is flagged `linkVerified: false` so the UI can say so
 * instead of pretending an unverified link is the real problem page.
 */
export const VERIFIED_LINKS: Record<string, string> = {
  // ---- Arrays ----
  "Largest Element in an Array": "https://www.geeksforgeeks.org/problems/largest-element-in-array4009/1",
  "Check if the array is sorted": "https://leetcode.com/problems/check-if-array-is-sorted-and-rotated/",
  "Remove duplicates from Sorted array": "https://leetcode.com/problems/remove-duplicates-from-sorted-array/",
  "Left Rotate an array by one place": "https://www.geeksforgeeks.org/problems/cyclically-rotate-an-array-by-one2614/1",
  "Left rotate an array by D places": "https://leetcode.com/problems/rotate-array/",
  "Move Zeros to end": "https://leetcode.com/problems/move-zeroes/",
  "Linear Search": "https://www.geeksforgeeks.org/problems/searching-a-number0324/1",
  "Find missing number in an array": "https://leetcode.com/problems/missing-number/",
  "Maximum Consecutive Ones": "https://leetcode.com/problems/max-consecutive-ones/",
  "Find the number that appears once, and other numbers twice": "https://leetcode.com/problems/single-number/",
  "Longest subarray with given sum K(positives)": "https://www.geeksforgeeks.org/problems/longest-sub-array-with-sum-k0809/1",
  "Longest subarray with sum K (Positives + Negatives)": "https://www.geeksforgeeks.org/problems/longest-sub-array-with-sum-k0809/1",
  "2Sum Problem": "https://leetcode.com/problems/two-sum/",
  "Sort an array of 0's 1's and 2's": "https://leetcode.com/problems/sort-colors/",
  "Majority Element (>n/2 times)": "https://leetcode.com/problems/majority-element/",
  "Kadane's Algorithm, maximum subarray sum": "https://leetcode.com/problems/maximum-subarray/",
  "Stock Buy and Sell": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
  "Rearrange the array in alternating positive and negative items": "https://leetcode.com/problems/rearrange-array-elements-by-sign/",
  "Next Permutation": "https://leetcode.com/problems/next-permutation/",
  "Leaders in an Array problem": "https://www.geeksforgeeks.org/problems/leaders-in-an-array-1587115620/1",
  "Longest Consecutive Sequence in an Array": "https://leetcode.com/problems/longest-consecutive-sequence/",
  "Set Matrix Zeros": "https://leetcode.com/problems/set-matrix-zeroes/",
  "Rotate Matrix by 90 degrees": "https://leetcode.com/problems/rotate-image/",
  "Print the matrix in spiral manner": "https://leetcode.com/problems/spiral-matrix/",
  "Count subarrays with given sum": "https://leetcode.com/problems/subarray-sum-equals-k/",
  "Pascal's Triangle": "https://leetcode.com/problems/pascals-triangle/",
  "Majority Element (n/3 times)": "https://leetcode.com/problems/majority-element-ii/",
  "3-Sum Problem": "https://leetcode.com/problems/3sum/",
  "4-Sum Problem": "https://leetcode.com/problems/4sum/",
  "Merge Overlapping Sub-intervals": "https://leetcode.com/problems/merge-intervals/",
  "Merge two sorted arrays without extra space": "https://leetcode.com/problems/merge-sorted-array/",
  "Find the repeating and missing number": "https://www.geeksforgeeks.org/problems/find-missing-and-repeating2512/1",
  "Count Inversions": "https://www.geeksforgeeks.org/problems/inversion-of-array-1587115620/1",
  "Reverse Pairs": "https://leetcode.com/problems/reverse-pairs/",
  "Maximum Product Subarray": "https://leetcode.com/problems/maximum-product-subarray/",

  // ---- Binary Search ----
  "Binary Search to find X in sorted array": "https://leetcode.com/problems/binary-search/",
  "Implement Lower Bound": "https://www.geeksforgeeks.org/problems/floor-in-a-sorted-array-1587115620/1",
  "Search Insert Position": "https://leetcode.com/problems/search-insert-position/",
  "Find the first or last occurrence of a given number in a sorted array":
    "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/",
  "Search in Rotated Sorted Array I": "https://leetcode.com/problems/search-in-rotated-sorted-array/",
  "Search in Rotated Sorted Array II": "https://leetcode.com/problems/search-in-rotated-sorted-array-ii/",
  "Find minimum in Rotated Sorted Array": "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
  "Single element in a Sorted Array": "https://leetcode.com/problems/single-element-in-a-sorted-array/",
  "Find peak element": "https://leetcode.com/problems/find-peak-element/",
  "Find square root of a number in log n": "https://leetcode.com/problems/sqrtx/",
  "Koko Eating Bananas": "https://leetcode.com/problems/koko-eating-bananas/",
  "Minimum days to make M bouquets": "https://leetcode.com/problems/minimum-number-of-days-to-make-m-bouquets/",
  "Find the smallest Divisor": "https://leetcode.com/problems/find-the-smallest-divisor-given-a-threshold/",
  "Capacity to Ship Packages within D Days": "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/",
  "Kth Missing Positive Number": "https://leetcode.com/problems/kth-missing-positive-number/",
  "Aggressive Cows": "https://www.geeksforgeeks.org/problems/aggressive-cows/1",
  "Book Allocation Problem": "https://www.geeksforgeeks.org/problems/allocate-minimum-number-of-pages0937/1",
  "Split array - Largest Sum": "https://leetcode.com/problems/split-array-largest-sum/",
  "Median of 2 sorted arrays": "https://leetcode.com/problems/median-of-two-sorted-arrays/",
  "Find the row with maximum number of 1's": "https://www.geeksforgeeks.org/problems/row-with-max-1s0023/1",
  "Search in a 2D matrix": "https://leetcode.com/problems/search-a-2d-matrix/",
  "Search in a row and column wise sorted matrix": "https://leetcode.com/problems/search-a-2d-matrix-ii/",
  "Find Peak Element (2D Matrix)": "https://leetcode.com/problems/find-a-peak-element-ii/",

  // ---- Strings ----
  "Remove outermost Paranthesis": "https://leetcode.com/problems/remove-outermost-parentheses/",
  "Reverse words in a given string / Palindrome Check": "https://leetcode.com/problems/reverse-words-in-a-string/",
  "Largest odd number in a string": "https://leetcode.com/problems/largest-odd-number-in-string/",
  "Longest Common Prefix": "https://leetcode.com/problems/longest-common-prefix/",
  "Isomorphic String": "https://leetcode.com/problems/isomorphic-strings/",
  "check whether one string is a rotation of another": "https://leetcode.com/problems/rotate-string/",
  "Check if two strings are anagram of each other": "https://leetcode.com/problems/valid-anagram/",
  "Sort Characters by frequency": "https://leetcode.com/problems/sort-characters-by-frequency/",
  "Maximum Nesting Depth of Paranthesis": "https://leetcode.com/problems/maximum-nesting-depth-of-the-parentheses/",
  "Roman Number to Integer and vice versa": "https://leetcode.com/problems/roman-to-integer/",
  "Implement Atoi": "https://leetcode.com/problems/string-to-integer-atoi/",
  "Count Number of Substrings": "https://leetcode.com/problems/subarrays-with-k-different-integers/",
  "Longest Palindromic Substring[Do it without DP]": "https://leetcode.com/problems/longest-palindromic-substring/",
  "Sum of Beauty of all substring": "https://leetcode.com/problems/sum-of-beauty-of-all-substrings/",
  "Reverse Every Word in A String": "https://leetcode.com/problems/reverse-words-in-a-string/",
  "Count and say": "https://leetcode.com/problems/count-and-say/",
  "Shortest Palindrome": "https://leetcode.com/problems/shortest-palindrome/",
  "Longest happy prefix": "https://leetcode.com/problems/longest-happy-prefix/",

  // ---- Linked List ----
  "Reverse a LinkedList [Iterative]": "https://leetcode.com/problems/reverse-linked-list/",
  "Reverse a LL [Recursive]": "https://leetcode.com/problems/reverse-linked-list/",
  "Find the middle element of the LL": "https://leetcode.com/problems/middle-of-the-linked-list/",
  "Detect a loop in LL": "https://leetcode.com/problems/linked-list-cycle/",
  "Find the starting point in LL": "https://leetcode.com/problems/linked-list-cycle-ii/",
  "Check if LL is palindrome or not": "https://leetcode.com/problems/palindrome-linked-list/",
  "Remove Nth node from the back of the LL": "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
  "Delete the middle node of LL": "https://leetcode.com/problems/delete-the-middle-node-of-a-linked-list/",
  "Sort LL": "https://leetcode.com/problems/sort-list/",
  "Add two numbers in LL": "https://leetcode.com/problems/add-two-numbers/",
  "Merge two sorted linked lists": "https://leetcode.com/problems/merge-two-sorted-lists/",
  "Flattening of LL": "https://www.geeksforgeeks.org/problems/flattening-a-linked-list/1",
  "Find intersection point of Y LL": "https://leetcode.com/problems/intersection-of-two-linked-lists/",
  "Rotate a LL": "https://leetcode.com/problems/rotate-list/",
  "Clone a Linked List with random and next pointer": "https://leetcode.com/problems/copy-list-with-random-pointer/",
  "Reverse LL in group of given size K": "https://leetcode.com/problems/reverse-nodes-in-k-group/",
  "Merge K sorted Linked lists": "https://leetcode.com/problems/merge-k-sorted-lists/",

  // ---- Recursion / Backtracking ----
  "Subset Sum : Sum of all Subsets": "https://www.geeksforgeeks.org/problems/subset-sums2234/1",
  "Subset - II ( Print unique subsets )": "https://leetcode.com/problems/subsets-ii/",
  "Combination Sum - 1": "https://leetcode.com/problems/combination-sum/",
  "Combination Sum - 2": "https://leetcode.com/problems/combination-sum-ii/",
  "Combination Sum - 3": "https://leetcode.com/problems/combination-sum-iii/",
  "Palindrome Partitioning": "https://leetcode.com/problems/palindrome-partitioning/",
  "Letter Combinations of a Phone Number": "https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
  "N Queen": "https://leetcode.com/problems/n-queens/",
  "Sudoko Solver": "https://leetcode.com/problems/sudoku-solver/",
  "Word Search": "https://leetcode.com/problems/word-search/",
  "M Coloring Problem": "https://www.geeksforgeeks.org/problems/m-coloring-problem-1587115620/1",
  "Rat in a Maze": "https://www.geeksforgeeks.org/problems/rat-in-a-maze-problem/1",
  "Generate all binary strings": "https://leetcode.com/problems/letter-case-permutation/",
  "Generate Paranthesis": "https://leetcode.com/problems/generate-parentheses/",

  // ---- Stacks & Queues ----
  "Implement Stack using Arrays": "https://www.geeksforgeeks.org/problems/implement-stack-using-array/1",
  "Implement Queue using Arrays": "https://www.geeksforgeeks.org/problems/implement-queue-using-array/1",
  "Implement Stack using Queue": "https://leetcode.com/problems/implement-stack-using-queues/",
  "Implement Queue using Stack": "https://leetcode.com/problems/implement-queue-using-stacks/",
  "Check for balanced paranthesis": "https://leetcode.com/problems/valid-parentheses/",
  "Implement Min Stack": "https://leetcode.com/problems/min-stack/",
  "Next Greater Element": "https://leetcode.com/problems/next-greater-element-i/",
  "Next Greater Element 2": "https://leetcode.com/problems/next-greater-element-ii/",
  "Trapping Rainwater": "https://leetcode.com/problems/trapping-rain-water/",
  "Sum of subarray minimum": "https://leetcode.com/problems/sum-of-subarray-minimums/",
  "Asteroid Collision": "https://leetcode.com/problems/asteroid-collision/",
  "Sum of subarray ranges": "https://leetcode.com/problems/sum-of-subarray-ranges/",
  "Remove k Digits": "https://leetcode.com/problems/remove-k-digits/",
  "Largest rectangle in a histogram": "https://leetcode.com/problems/largest-rectangle-in-histogram/",
  "Maximal Rectangles": "https://leetcode.com/problems/maximal-rectangle/",
  "Sliding Window maximum": "https://leetcode.com/problems/sliding-window-maximum/",
  "LRU cache (IMPORTANT)": "https://leetcode.com/problems/lru-cache/",
  "LFU cache": "https://leetcode.com/problems/lfu-cache/",
  "The Celebrity Problem": "https://www.geeksforgeeks.org/problems/the-celebrity-problem/1",
  "Online Stock Span": "https://leetcode.com/problems/online-stock-span/",

  // ---- Sliding window ----
  "Longest Substring Without Repeating Characters": "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
  "Max Consecutive Ones III": "https://leetcode.com/problems/max-consecutive-ones-iii/",
  "Fruit Into Baskets": "https://leetcode.com/problems/fruit-into-baskets/",
  "Longest repeating character replacement": "https://leetcode.com/problems/longest-repeating-character-replacement/",
  "Binary subarray with sum": "https://leetcode.com/problems/binary-subarrays-with-sum/",
  "Count number of nice subarrays": "https://leetcode.com/problems/count-number-of-nice-subarrays/",
  "Number of substring containing all three characters": "https://leetcode.com/problems/number-of-substrings-containing-all-three-characters/",
  "Maximum point you can obtain from cards": "https://leetcode.com/problems/maximum-points-you-can-obtain-from-cards/",
  "Subarray with k different integers": "https://leetcode.com/problems/subarrays-with-k-different-integers/",
  "Minimum Window Substring": "https://leetcode.com/problems/minimum-window-substring/",

  // ---- Heaps ----
  "Kth largest element in an array": "https://leetcode.com/problems/kth-largest-element-in-an-array/",
  "Merge M sorted Lists": "https://leetcode.com/problems/merge-k-sorted-lists/",
  "Task Scheduler": "https://leetcode.com/problems/task-scheduler/",
  "Hands of Straights": "https://leetcode.com/problems/hand-of-straights/",
  "Design twitter": "https://leetcode.com/problems/design-twitter/",
  "Kth largest element in a stream of running integers": "https://leetcode.com/problems/kth-largest-element-in-a-stream/",
  "Find Median from Data Stream": "https://leetcode.com/problems/find-median-from-data-stream/",
  "K most frequent elements": "https://leetcode.com/problems/top-k-frequent-elements/",

  // ---- Greedy ----
  "Assign Cookies": "https://leetcode.com/problems/assign-cookies/",
  "Lemonade Change": "https://leetcode.com/problems/lemonade-change/",
  "Valid Paranthesis Checker": "https://leetcode.com/problems/valid-parenthesis-string/",
  "Jump Game": "https://leetcode.com/problems/jump-game/",
  "Jump Game 2": "https://leetcode.com/problems/jump-game-ii/",
  "Candy": "https://leetcode.com/problems/candy/",
  "Insert Interval": "https://leetcode.com/problems/insert-interval/",
  "Merge Intervals": "https://leetcode.com/problems/merge-intervals/",
  "Non-overlapping Intervals": "https://leetcode.com/problems/non-overlapping-intervals/",
  "N meetings in one room": "https://www.geeksforgeeks.org/problems/n-meetings-in-one-room-1587115620/1",
  "Fractional Knapsack Problem": "https://www.geeksforgeeks.org/problems/fractional-knapsack-1587115620/1",
  "Minimum number of platforms required for a railway": "https://www.geeksforgeeks.org/problems/minimum-platforms-1587115620/1",
  "Job sequencing Problem": "https://www.geeksforgeeks.org/problems/job-sequencing-problem-1587115620/1",

  // ---- Binary Trees / BST ----
  "Preorder Traversal of Binary Tree": "https://leetcode.com/problems/binary-tree-preorder-traversal/",
  "Inorder Traversal of Binary Tree": "https://leetcode.com/problems/binary-tree-inorder-traversal/",
  "Post-order Traversal of Binary Tree": "https://leetcode.com/problems/binary-tree-postorder-traversal/",
  "Level order Traversal / Level order traversal in spiral form": "https://leetcode.com/problems/binary-tree-level-order-traversal/",
  "Height of a Binary Tree": "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
  "Check if the Binary tree is height-balanced or not": "https://leetcode.com/problems/balanced-binary-tree/",
  "Diameter of Binary Tree": "https://leetcode.com/problems/diameter-of-binary-tree/",
  "Maximum path sum": "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
  "Check if two trees are identical or not": "https://leetcode.com/problems/same-tree/",
  "Zig Zag Traversal of Binary Tree": "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/",
  "Right/Left view of Binary Tree": "https://leetcode.com/problems/binary-tree-right-side-view/",
  "Symmetric Binary Tree": "https://leetcode.com/problems/symmetric-tree/",
  "Root to Node Path in Binary Tree": "https://www.geeksforgeeks.org/problems/root-to-leaf-paths/1",
  "LCA in Binary Tree": "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/",
  "Maximum width of a Binary Tree": "https://leetcode.com/problems/maximum-width-of-binary-tree/",
  "Count total Nodes in a COMPLETE Binary Tree": "https://leetcode.com/problems/count-complete-tree-nodes/",
  "Construct Binary Tree from inorder and preorder": "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/",
  "Construct the Binary Tree from Postorder and Inorder Traversal": "https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/",
  "Serialize and deserialize Binary Tree": "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
  "Flatten Binary Tree to LinkedList": "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/",
  "Search in a Binary Search Tree": "https://leetcode.com/problems/search-in-a-binary-search-tree/",
  "Find Min/Max in BST": "https://www.geeksforgeeks.org/problems/minimum-element-in-bst/1",
  "Ceil in a Binary Search Tree": "https://www.geeksforgeeks.org/problems/implementing-ceil-in-bst/1",
  "Floor in a Binary Search Tree": "https://www.geeksforgeeks.org/problems/floor-in-bst/1",
  "Insert a given Node in Binary Search Tree": "https://leetcode.com/problems/insert-into-a-binary-search-tree/",
  "Delete a Node in Binary Search Tree": "https://leetcode.com/problems/delete-node-in-a-bst/",
  "Find K-th smallest/largest element in BST": "https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
  "Check if a tree is a BST or BT": "https://leetcode.com/problems/validate-binary-search-tree/",
  "LCA in Binary Search Tree": "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
  "Construct a BST from a preorder traversal": "https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal/",
  "Inorder Successor/Predecessor in BST": "https://www.geeksforgeeks.org/problems/predecessor-and-successor/1",
  "Binary Search Tree Iterator": "https://leetcode.com/problems/binary-search-tree-iterator/",
  "Two Sum In BST | Check if there exists a pair with Sum K": "https://leetcode.com/problems/two-sum-iv-input-is-a-bst/",
  "Recover BST | Correct BST with two nodes swapped": "https://leetcode.com/problems/recover-binary-search-tree/",
  "Largest BST in Binary Tree": "https://www.geeksforgeeks.org/problems/largest-bst/1",

  // ---- Graphs ----
  "BFS of graph": "https://www.geeksforgeeks.org/problems/bfs-traversal-of-graph/1",
  "DFS of Graph": "https://www.geeksforgeeks.org/problems/depth-first-traversal-for-a-graph/1",
  "Number of provinces": "https://leetcode.com/problems/number-of-provinces/",
  "Number of Islands": "https://leetcode.com/problems/number-of-islands/",
  "Flood fill": "https://leetcode.com/problems/flood-fill/",
  "Rotten Oranges": "https://leetcode.com/problems/rotting-oranges/",
  "Surrounded Regions": "https://leetcode.com/problems/surrounded-regions/",
  "Word ladder - 1": "https://leetcode.com/problems/word-ladder/",
  "Word ladder - 2": "https://leetcode.com/problems/word-ladder-ii/",
  "Course Schedule - I": "https://leetcode.com/problems/course-schedule/",
  "Course Schedule - II": "https://leetcode.com/problems/course-schedule-ii/",
  "Alien dictionary": "https://www.geeksforgeeks.org/problems/alien-dictionary/1",
  "Cheapest flights within k stops": "https://leetcode.com/problems/cheapest-flights-within-k-stops/",
  "Network Delay time": "https://leetcode.com/problems/network-delay-time/",
  "Number of ways to arrive at destination": "https://leetcode.com/problems/number-of-ways-to-arrive-at-destination/",
  "Path with minimum effort": "https://leetcode.com/problems/path-with-minimum-effort/",
  "Shortest path in a binary maze": "https://leetcode.com/problems/shortest-path-in-binary-matrix/",
  "Number of Distinct Islands": "https://www.geeksforgeeks.org/problems/number-of-distinct-islands/1",
  "Bipartite Graph": "https://leetcode.com/problems/is-graph-bipartite/",
  "Critical Connections in a Network": "https://leetcode.com/problems/critical-connections-in-a-network/",
  "Number of operations to make network connected": "https://leetcode.com/problems/number-of-operations-to-make-network-connected/",
  "Accounts merge": "https://leetcode.com/problems/accounts-merge/",
  "Making a Large Island": "https://leetcode.com/problems/making-a-large-island/",
  "Most stones removed with same rows or columns": "https://leetcode.com/problems/most-stones-removed-with-same-row-or-column/",
  "Swim in rising water": "https://leetcode.com/problems/swim-in-rising-water/",

  // ---- Dynamic Programming ----
  "Climbing Stars": "https://leetcode.com/problems/climbing-stairs/",
  "House Robber": "https://leetcode.com/problems/house-robber/",
  "House Robber 2": "https://leetcode.com/problems/house-robber-ii/",
  "Triangle": "https://leetcode.com/problems/triangle/",
  "Minimum path sum in Grid": "https://leetcode.com/problems/minimum-path-sum/",
  "Grid Unique Paths": "https://leetcode.com/problems/unique-paths/",
  "Grid Unique Paths 2": "https://leetcode.com/problems/unique-paths-ii/",
  "Coin Change": "https://leetcode.com/problems/coin-change/",
  "Partition Equal Subset Sum": "https://leetcode.com/problems/partition-equal-subset-sum/",
  "Target Sum": "https://leetcode.com/problems/target-sum/",
  "Coin Change 2": "https://leetcode.com/problems/coin-change-ii/",
  "Longest Common Subsequence": "https://leetcode.com/problems/longest-common-subsequence/",
  "Longest Palindromic Subsequence": "https://leetcode.com/problems/longest-palindromic-subsequence/",
  "Edit Distance": "https://leetcode.com/problems/edit-distance/",
  "Wildcard Matching": "https://leetcode.com/problems/wildcard-matching/",
  "Distinct Subsequences": "https://leetcode.com/problems/distinct-subsequences/",
  "Best time to buy and sell stock": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
  "Buy and sell stock - II": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/",
  "Buy and sell stocks III": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/",
  "Buy and stock sell IV": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/",
  "Buy and sell stocks with cooldown": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/",
  "Buy and sell stocks with transaction fee": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-transaction-fee/",
  "Longest Increasing Subsequence": "https://leetcode.com/problems/longest-increasing-subsequence/",
  "Number of longest increasing subsequences": "https://leetcode.com/problems/number-of-longest-increasing-subsequence/",
  "Longest String Chain": "https://leetcode.com/problems/longest-string-chain/",
  "Matrix Chain Multiplication": "https://www.geeksforgeeks.org/problems/matrix-chain-multiplication0303/1",
  "Burst Balloons": "https://leetcode.com/problems/burst-balloons/",
  "Palindrome Partitioning - II": "https://leetcode.com/problems/palindrome-partitioning-ii/",
  "Maximal Rectangle": "https://leetcode.com/problems/maximal-rectangle/",
  "Count Square Submatrices with All Ones": "https://leetcode.com/problems/count-square-submatrices-with-all-ones/",

  // ---- Tries / Bit manipulation / Maths ----
  "Implement TRIE | INSERT | SEARCH | STARTSWITH": "https://leetcode.com/problems/implement-trie-prefix-tree/",
  "Maximum XOR of two numbers in an array": "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/",
  "Maximum XOR With an Element From Array": "https://leetcode.com/problems/maximum-xor-with-an-element-from-array/",
  "Number of 1 Bits": "https://leetcode.com/problems/number-of-1-bits/",
  "Single Number II": "https://leetcode.com/problems/single-number-ii/",
  "Single Number III": "https://leetcode.com/problems/single-number-iii/",
  "Power Set": "https://leetcode.com/problems/subsets/",
  "Divide two integers without using multiplication, division and mod operator":
    "https://leetcode.com/problems/divide-two-integers/",
  "Count Primes": "https://leetcode.com/problems/count-primes/",
  "Pow(x, n)": "https://leetcode.com/problems/powx-n/",
  "Reverse Integer": "https://leetcode.com/problems/reverse-integer/",
  "Excel Sheet Column Title": "https://leetcode.com/problems/excel-sheet-column-title/",
};

export const isLinkVerified = (name: string) => Boolean(VERIFIED_LINKS[name]);
