/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedBacklogRouteImport } from './routes/_authenticated/backlog'
import { Route as AuthenticatedContestsRouteImport } from './routes/_authenticated/contests'
import { Route as AuthenticatedProblemsRouteImport } from './routes/_authenticated/problems'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedReviewRouteImport } from './routes/_authenticated/review'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedTopicsRouteImport } from './routes/_authenticated/topics'
import { Route as AuthenticatedWeeksRouteImport } from './routes/_authenticated/weeks'
import { Route as AuthenticatedDayDayNumberRouteImport } from './routes/_authenticated/day.$dayNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBacklogRoute = AuthenticatedBacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContestsRoute = AuthenticatedContestsRouteImport.update({
  id: '/contests',
  path: '/contests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProblemsRoute = AuthenticatedProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewRoute = AuthenticatedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTopicsRoute = AuthenticatedTopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWeeksRoute = AuthenticatedWeeksRouteImport.update({
  id: '/weeks',
  path: '/weeks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDayDayNumberRoute =
  AuthenticatedDayDayNumberRouteImport.update({
    id: '/day/$dayNumber',
    path: '/day/$dayNumber',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/backlog': typeof AuthenticatedBacklogRoute
  '/contests': typeof AuthenticatedContestsRoute
  '/problems': typeof AuthenticatedProblemsRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/review': typeof AuthenticatedReviewRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/today': typeof AuthenticatedTodayRoute
  '/topics': typeof AuthenticatedTopicsRoute
  '/weeks': typeof AuthenticatedWeeksRoute
  '/day/$dayNumber': typeof AuthenticatedDayDayNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/backlog': typeof AuthenticatedBacklogRoute
  '/contests': typeof AuthenticatedContestsRoute
  '/problems': typeof AuthenticatedProblemsRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/review': typeof AuthenticatedReviewRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/today': typeof AuthenticatedTodayRoute
  '/topics': typeof AuthenticatedTopicsRoute
  '/weeks': typeof AuthenticatedWeeksRoute
  '/day/$dayNumber': typeof AuthenticatedDayDayNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/backlog': typeof AuthenticatedBacklogRoute
  '/_authenticated/contests': typeof AuthenticatedContestsRoute
  '/_authenticated/problems': typeof AuthenticatedProblemsRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/review': typeof AuthenticatedReviewRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/topics': typeof AuthenticatedTopicsRoute
  '/_authenticated/weeks': typeof AuthenticatedWeeksRoute
  '/_authenticated/day/$dayNumber': typeof AuthenticatedDayDayNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/backlog'
    | '/contests'
    | '/problems'
    | '/progress'
    | '/review'
    | '/settings'
    | '/today'
    | '/topics'
    | '/weeks'
    | '/day/$dayNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/backlog'
    | '/contests'
    | '/problems'
    | '/progress'
    | '/review'
    | '/settings'
    | '/today'
    | '/topics'
    | '/weeks'
    | '/day/$dayNumber'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/backlog'
    | '/_authenticated/contests'
    | '/_authenticated/problems'
    | '/_authenticated/progress'
    | '/_authenticated/review'
    | '/_authenticated/settings'
    | '/_authenticated/today'
    | '/_authenticated/topics'
    | '/_authenticated/weeks'
    | '/_authenticated/day/$dayNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/backlog': {
      id: '/_authenticated/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof AuthenticatedBacklogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contests': {
      id: '/_authenticated/contests'
      path: '/contests'
      fullPath: '/contests'
      preLoaderRoute: typeof AuthenticatedContestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/problems': {
      id: '/_authenticated/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof AuthenticatedProblemsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review': {
      id: '/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/topics': {
      id: '/_authenticated/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof AuthenticatedTopicsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/weeks': {
      id: '/_authenticated/weeks'
      path: '/weeks'
      fullPath: '/weeks'
      preLoaderRoute: typeof AuthenticatedWeeksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/day/$dayNumber': {
      id: '/_authenticated/day/$dayNumber'
      path: '/day/$dayNumber'
      fullPath: '/day/$dayNumber'
      preLoaderRoute: typeof AuthenticatedDayDayNumberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBacklogRoute: typeof AuthenticatedBacklogRoute
  AuthenticatedContestsRoute: typeof AuthenticatedContestsRoute
  AuthenticatedProblemsRoute: typeof AuthenticatedProblemsRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedReviewRoute: typeof AuthenticatedReviewRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedTopicsRoute: typeof AuthenticatedTopicsRoute
  AuthenticatedWeeksRoute: typeof AuthenticatedWeeksRoute
  AuthenticatedDayDayNumberRoute: typeof AuthenticatedDayDayNumberRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBacklogRoute: AuthenticatedBacklogRoute,
  AuthenticatedContestsRoute: AuthenticatedContestsRoute,
  AuthenticatedProblemsRoute: AuthenticatedProblemsRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedReviewRoute: AuthenticatedReviewRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedTopicsRoute: AuthenticatedTopicsRoute,
  AuthenticatedWeeksRoute: AuthenticatedWeeksRoute,
  AuthenticatedDayDayNumberRoute: AuthenticatedDayDayNumberRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
